server:
  port: 8080
hibernate:
  show_sql: 'true'
spring:
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    password: ''
    user: root
    url: jdbc:mysql://localhost:3306/spring_jpa
    driver-class-name: com.mysql.jdbc.Driver