spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password:
        url: jdbc:mysql://localhost:3306/pakimonsuperdefinitivo

    jpa:
        generate-ddl: 'true'
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: update